### ISSUE TITLE
Switch network improvement 

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/od-app#2]
The prompt to switch networks should call the Metamask RPC to switch networks, rather than direct the user to chainlist

![image](https://github.com/UseKeyp/open-dollar-app/assets/35622595/491f8000-ba0e-4349-b252-ccdcff5c44cd)

**Comment by pi0neerpat** [comment]
I get the prompt every time, even when I'm on the right network now.

**Comment by jahabeebs** [comment]
> I get the prompt every time, even when I'm on the right network now.

what branch are you working on and what browser do you use? I can't reproduce it happening when the network is optimism goerli. I've tried on chrome and firefox

on right network:

https://github.com/UseKeyp/od-app/assets/47253537/82410d5d-d153-4bc0-b4f9-4e50ca68d782

switching networks:

https://github.com/UseKeyp/od-app/assets/47253537/8e67710e-7f48-40fb-aad7-b672b2c9d4c3

**Comment by pi0neerpat** [comment]
I am still getting the prompt to switch. To reproduce: add your own optimism-goerli network and use that one. Then disconnect your wallet in mm, and then connect to the app
 

![Image](https://github.com/UseKeyp/od-app/assets/35622595/52770c76-f63b-4001-9e9b-d1ad068cfcb5)

**Comment by pi0neerpat** [comment]
Yellow is the one I added. Green is the one that gets added by MM when I hit 'Approve' 

![Image](https://github.com/UseKeyp/od-app/assets/35622595/ffdcec01-16c1-44bd-96aa-ecc6caba5c35)
