### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/od-app#22]
Lets research which of these can be easily created using existing data

- total volume of transfers of token 
- fees earned by the protocol over time
- current debt of all vaults
- number of liquidations
- liquidation $ total amount

for anything requiring subgraph, lets note that in https://github.com/UseKeyp/open-dollar-app/issues/21

Ideas from https://app.bean.money/

**Comment by jahabeebs** [comment]
> Lets research which of these can be easily created using existing data
> 
>     * total volume of transfers of token
> 
>     * fees earned by the protocol over time
> 
>     * current debt of all vaults
> 
>     * number of liquidations
> 
>     * liquidation $ total amount
> 
> 
> for anything requiring subgraph, lets note that in #21
> 
> Ideas from https://app.bean.money/

I added most of my research to https://github.com/UseKeyp/open-dollar-app/issues/21

- total volume of transfers of token

Did not find anything on transfers, but there's amount issued for a given token here: https://stats.reflexer.finance/ 
I believe the data in https://stats.reflexer.finance/ is coming from https://github.com/reflexer-labs/geb-data-science but I would have to talk to them about how they're running it/if they're getting the data from elsewhere

- fees earned by the protocol over time

Did not see this in any of the stats. we would have to estimate based off of amount in each safe * stability fee

- current debt of all vaults

easy to get, see here: https://reflexer-stat-dashboard-git-cr-manolingam.vercel.app/

- number of liquidations

Did not see this in any of the stats. maybe could calculate with [CollateralType_filter](https://subgraph.reflexer.finance/subgraphs/name/reflexer-labs/rai/graphql?query=#).activeLiquidations_in ?

- liquidation $ total amount

Same as ^, no easy info about liquidations exposed
