### ISSUE TITLE
Styling changes

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/od-app#24]
## Heading

![image](https://github.com/UseKeyp/open-dollar-app/assets/35622595/f4d9ace2-53d8-4af7-978c-2cfa0ed10b7e)

- new brand mark
- Token balance asset name and icon

## App page 

- background color change

## Vaults list

![image](https://github.com/UseKeyp/open-dollar-app/assets/35622595/803ca5e1-3428-4297-9603-ed93ab3de95e)

- Each column is now right-aligned layount
- risk label is now within the row
- outer box around rows of vaults is now transparent
- renamed all "safe" reference to 'vault'
- Button
- Row color different

## Vault details

![image](https://github.com/UseKeyp/open-dollar-app/assets/35622595/057f8a79-5782-47dc-8499-5e466fe18a36)

- fonts style change to Inter (should be Inter across the whole app)
- background colors updated
- Depost + Repay tab switcher buttons moved

**Comment by alekseevaiana** [comment]
Put the link to a design file for the convenience 
https://www.figma.com/file/uJdTlxdVIJNozrmGtqQQvq/OpenDollar-App?type=design&node-id=480%3A423&mode=design&t=fDPep16kiovKk9Ha-1
