### ISSUE TITLE
Wallet options

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/od-app#45]
Add config needed for wallet connect and coinbase wallet option

**Comment by jahabeebs** [comment]
@pi0neerpat Just as an update on this issue, I was able to get the WalletConnect and Coinbase modals showing by polyfilling buffer & util but there are a couple issues:

1) WalletConnect eliminated their v1 so now we have to migrate to v2 (meaning no more bridge.walletconnect as a URL, need a projectId now, no longer compatible w/@web3-react/walletconnect-connector which is what the connector logic is built around) so we have to build that up from scratch 

2) I think related to the fact that @web3-react/walletconnect-connector  is out of date (there's a web3-react/coinbase package now), Coinbase wallet throws general ethers errors once connected. maybe it's trying to change networks and can't w/the current package, or maybe the polyfill isn't sufficient

So we will need to gut the current connector logic to use the new libraries: specifically web3-react/walletconnect-v2 and web3-react/coinbase-wallet. I'll be giving this a try

**Comment by pi0neerpat** [comment]
Done
