### ISSUE TITLE
Stats page 

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/od-app#60]
- Update the stats page "analytics" boxes to new design. 
- Please create a plan detailing each box, where the data is coming from, and which pieces of data are currently missing. 

![image](https://github.com/UseKeyp/od-app/assets/35622595/0b6c9000-0713-4b60-9c65-2071fc80e2e1)

**Comment by alekseevaiana** [comment]
You can find below sub headers with data we need and what we already have. I put `missing` for data that I couldn't find over the app. 

**Anslytics**
_Total Collateral Locked - missing_
_Outstanding OD - missing_
_Vault NFTs - missing_

**System Rates**
Annual Stability Fee -> annualRate (from toke stability fee)
Annual Redemption Rate -> annualRedemptionRate
8-hour redemption rate  -> eightRate

**System Info**
_Circulation - missing_
_Fees Pending Auction - missing_
_Total Fees Earned - missing_
Gloal debt utilization -> globalDebtUtilization
global debt - globalDebt

**Prices**
Market Price OD - have but about hai -> marketPrice
redemption Price OD - have but about hai
_OD/ETH Liquidity in uniswap - missing_ 
_Market Price ODG - missing_

**Comment by pi0neerpat** [comment]
Looks good to go! We can talk data on our next call.
