### ISSUE TITLE
Change HAI to OD

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/od-app#8]
Our stable token is named "OD" (this may change)

The app should be updated to display OD instead of HAI

![Image](https://github.com/UseKeyp/open-dollar-app/assets/35622595/0dd9dfb4-3a3f-419b-a92a-3e7c9c4b0896)

**Comment by pi0neerpat** [comment]
Reopening, as the page title was missed. Please ensure the meta tags are updated as well 

![Image](https://github.com/UseKeyp/open-dollar-app/assets/35622595/c2fe5943-8dac-4f60-b1d9-ae6dfc7ac256)

**Comment by alekseevaiana** [comment]
I updated the title, but I don't see what to update in meta tags. Do I update icons to a new ones?
