### ISSUE TITLE
QA - OD 0.9999 issue

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/od-app#84]
OD borrowed was 10, but app is showing 9.99955

- [ ] Check what happened on-chain
- [ ] Update the app rounding, if thats what caused the issue

**Comment by pi0neerpat** [comment]
The actual amount was 10 OD https://goerli.arbiscan.io/tx/0x7b5613baf41bfb94c30a41a3513aaf212a571dedf3bea73d2f4b91d06f4a4598

So some incorrect rounding is happening in the app

**Comment by alekseevaiana** [comment]
It seems that we get this string with decimals from the API, so our formatting functions not causing the issue. 

I put console.log in `safes.ts` in `fetchUserSafes` function and got this response:

![Image](https://github.com/UseKeyp/od-app/assets/36742189/3bdf3fd4-6aa1-4e65-bc51-b7e907c3d96f)
